global_costmap:
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 10
  width: 30
  height: 30
  static_map: false
  rolling_window: true
  inflation_radius: 0.8
  resolution: 0.05
  cost_scaling_factor: 2

