global_costmap:
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 10
  width: 15
  height: 15
  origin_x: -7.5
  origin_y: -7.5
  static_map: false
  rolling_window: true
  inflation_radius: 0.8
  resolution: 0.01
  cost_scaling_factor: 2

