local_costmap:
  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 10
  static_map: false
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.1
  inflation_radius: 1.0
  cost_scaling_factor: 1
