TrajectoryPlannerROS:
  max_vel_x: 0.1
  min_vel_x: 0.01
  max_vel_y: 0
  min_vel_y: 0
  max_vel_theta: 1
  min_vel_theta: -1
  min_in_place_vel_theta: 0.01

  acc_lim_theta: 2.0
  acc_lim_x: 0.1
  acc_lim_Y: 0

  holonomic_robot: false

  meter_scoring: true

  xy_goal_tolerance: 0.5
  yaw_goal_tolerance: 0.05
