# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_solver_interface', [dirname(__file__)])
        except ImportError:
            import _solver_interface
            return _solver_interface
        if fp is not None:
            try:
                _mod = imp.load_module('_solver_interface', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _solver_interface = swig_import_helper()
    del swig_import_helper
else:
    import _solver_interface
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def set_defaults():
    return _solver_interface.set_defaults()
set_defaults = _solver_interface.set_defaults

def setup_indexing():
    return _solver_interface.setup_indexing()
setup_indexing = _solver_interface.setup_indexing

def load_default_data():
    return _solver_interface.load_default_data()
load_default_data = _solver_interface.load_default_data

def solve():
    return _solver_interface.solve()
solve = _solver_interface.solve

def set_parameters(id, index, val):
    return _solver_interface.set_parameters(id, index, val)
set_parameters = _solver_interface.set_parameters

def visualize_parameters():
    return _solver_interface.visualize_parameters()
visualize_parameters = _solver_interface.visualize_parameters

def visualize_variables():
    return _solver_interface.visualize_variables()
visualize_variables = _solver_interface.visualize_variables

_solver_interface.CONTROL_DIM_swigconstant(_solver_interface)
CONTROL_DIM = _solver_interface.CONTROL_DIM

_solver_interface.STATE_DIM_swigconstant(_solver_interface)
STATE_DIM = _solver_interface.STATE_DIM

_solver_interface.HORIZON_swigconstant(_solver_interface)
HORIZON = _solver_interface.HORIZON

def set_ref(x, y):
    return _solver_interface.set_ref(x, y)
set_ref = _solver_interface.set_ref

def get_prediction_horizon():
    return _solver_interface.get_prediction_horizon()
get_prediction_horizon = _solver_interface.get_prediction_horizon

def get_control_horizon():
    return _solver_interface.get_control_horizon()
get_control_horizon = _solver_interface.get_control_horizon
# This file is compatible with both classic and new-style classes.

cvar = _solver_interface.cvar

